# Generated by Django 5.1.6 on 2025-12-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_newslettersubscriber_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newslettersubscriber",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="newslettersubscriber",
            name="unsubscribe_token",
        ),
    ]
