# Generated by Django 5.1.6 on 2025-03-23 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_file', models.FileField(blank=True, null=True, upload_to='training/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='training/thumbnails/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_free', models.BooleanField(default=False, help_text='Mark this video as free to view without a subscription')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='training.trainingcategory')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Training',
                'db_table': 'training_lesson',
            },
        ),
    ]
