# Generated by Django 5.1.6 on 2025-12-02 15:46

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="training",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "Training",
                "verbose_name_plural": "Training",
            },
        ),
        migrations.AlterModelOptions(
            name="trainingcategory",
            options={"verbose_name_plural": "Training Categories"},
        ),
        migrations.AlterField(
            model_name="training",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order (lower numbers appear first)"
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Upload video thumbnail image",
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="training/thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Upload training video file",
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to="training/videos/",
            ),
        ),
    ]
