# Generated by Django 5.1.6 on 2025-03-02 15:14

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_training_trainingcategory_delete_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='category',
            field=models.ForeignKey(
                to='training.TrainingCategory',
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='trainings',
                null=True,
                blank=True,
            ),
        ),
    ]
