# Generated by Django 5.1.6 on 2025-03-02 16:20

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20250302_1514'),
    ]

    operations = [
        # Create the TrainingCategory table
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True, blank=True)),
            ],
        ),
    ]
