# Generated by Django 5.1.6 on 2025-03-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20250302_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Mark this video as free to view without a subscription'),
        ),
    ]
