# Generated by Django 5.1.6 on 2025-12-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_stock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name_plural": "Product Categories"},
        ),
    ]
